### ISSUE TITLE
range

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/recupero_python#1]
Apri il terminale, lancia l'interprete python e fai qualche prova con `range()`
```bash
$ python
>>> range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> range(1, 10, 3)
[1, 4, 7]
>>> range(5, 0, -1)
[5, 4, 3, 2, 1]
```

In countdown_for.py trovi un esempio di ciclo for (usato in congiunzione con range)

**Comment by Teodoro777** [comment]
Cioè range() fa pure un for "automatico" nell'interprete... 
Alla fine nel programma range() funge da variabile. Ma se metto un'altra parola ad esempio "for i in intervallo()" da errore. Come mai?

**Comment by FabioZTessitore** [comment]
`range` restituisce una lista di numeri e il ciclo for itera su questa lista.

Non ho capito che tipo di errore ottieni, spiegati meglio o carica un codice

**Comment by Teodoro777** [comment]
Quindi cos'è range? Una funzione?

**Comment by FabioZTessitore** [comment]
certo. ci sono le parentesi

**Comment by Teodoro777** [comment]
Ok allora tutto ok
