### ISSUE TITLE
funzioni

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/recupero_python#2]
nel file hello.py trovi una funzione

apri l'interprete python e prova
```
>>> "hello" * 5
```

Prova a modificare la funzione eliminando il ciclo

**Comment by Teodoro777** [comment]
Piccola curiosità: come elimino l'ultimo fastidioso "a capo"?

**Comment by FabioZTessitore** [comment]
come sai print aggiunge automaticamente un a capo. nel tuo caso non è desiderato perché ci sono già i caratteri \n. si risolve mettendo una virgola
es
```python
print "hello"    # va a capo automaticamente
print "hello",   # questo no
```

**Comment by FabioZTessitore** [comment]
ho fatto un push, quindi fai il pull

**Comment by FabioZTessitore** [comment]
guarda il file twice.py
trovi un tipo di funzione che in C non puoi scrivere. Infatti il parametro `elem` può essere di qualsiasi tipo

**Comment by FabioZTessitore** [comment]
guarda il file tuple.py
un'altra cosa che in C non puoi fare è far ritornare più di un valore ad una funzione.

**Comment by Teodoro777** [comment]
Ok mi spiegate bene tutti i 3 tipi particolari del python?

**Comment by FabioZTessitore** [comment]
che sono i tipi particolari?

**Comment by Teodoro777** [comment]
Intendo le tuple, liste e dizionari.

**Comment by FabioZTessitore** [comment]
liste e dizionari ancora non li abbiamo affrontati.
riguardo alle tuple, è un modo per raggruppare valori.
```python
coordinate = (1.3, 3.9)
print "coordinata x:", coordinate[0]
```

**Comment by Teodoro777** [comment]
Ok capito.
