### ISSUE TITLE
distanza1

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/recupero_python#4]
creare un modulo e scrivere del codice per testarlo, vedi distance1.py

**Comment by Teodoro777** [comment]
Se non ce lo mettiamo quel `if __name__ = '__main__'` cosa succede?

**Comment by FabioZTessitore** [comment]
Se fai
python distance1.py
non cambia niente

Se invece fai l'import del file quel pezzo di codice non verrà eseguito
perché la variabile __name__ non assume il valore "__main__"

Il venerdì 28 ottobre 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Ah ok. 
Che modulo devo creare?

**Comment by FabioZTessitore** [comment]
Aspe

Il venerdì 28 ottobre 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Fatto?

**Comment by FabioZTessitore** [comment]
guarda distance2.py
utilizza un modulo per documentare e testare le funzioni
