### ISSUE TITLE
ipotenusa

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/recupero_python#5]
crea un modulo mymath e mettici dentro la funzione hypotenuse()
ricorda di creare dei test come in distance2.py

![es5_15](https://cloud.githubusercontent.com/assets/3002194/19820749/ff4fa85a-9d5a-11e6-9be4-f09aff2ebd4a.png)

**Comment by FabioZTessitore** [comment]
devi fare questo esercizio. mi raccomando il modulo mymath

**Comment by Teodoro777** [comment]
Piccola curiosità: se voglio stampare un carattere come " o ' in una print come posso fare, visto che così facendo chiude la stringa?

**Comment by FabioZTessitore** [comment]
basta farlo precedere da \
es
```c
printf("due parole \"tra virgolette\"\n");
```

**Comment by Teodoro777** [comment]
Okk

**Comment by FabioZTessitore** [comment]
si si

**Comment by Teodoro777** [comment]
Ho cancellato perchè ho notato che avete usato proprio il c nell'esempio ahah

**Comment by FabioZTessitore** [comment]
metti anche gli altri test come mostrato nella figura e metti un file .gitignore nella cartella principale

**Comment by Teodoro777** [comment]
Fatto
