### ISSUE TITLE
corona circolare

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/recupero_python#6]
scrivere una funzione che calcola l'area di una corona circolare

continua a usare mymath

**Comment by Teodoro777** [comment]
Come faccio ad approssimare i volori? Sia per il test che nel main quando stampo..

**Comment by FabioZTessitore** [comment]
vale la stessa cosa in entrambi i casi:
puoi usare round(numero, cifre) oppure se preferisci lo stile C '%.3f' % numero (mettendo al posto di 3 il numero di cifre che vuoi dopo la virgola)

ps. togli quei cm^2. Dove sta scritto che l'input è in cm?

ps. visto che stai creando un modulo, perché non calcoli l'area della corona circolare utilizzando altre aree geometriche. In questo modo il tuo modulo si arricchisce e diventa più utile

**Comment by Teodoro777** [comment]
cm^2 sta nell'output.. L'area la calcolo in cm^2

**Comment by FabioZTessitore** [comment]
ma quando vengono immessi i valori sono numeri puri, così tutti lo possono usare a prescindere dall'unità di misura

**Comment by Teodoro777** [comment]
Sisi infatti in input non ho messo niente

**Comment by FabioZTessitore** [comment]
appunto, non si capisce perché in output metti cm^2

**Comment by Teodoro777** [comment]
L'ho tolto..
