### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/recupero_python#7]
secondo te i termini

``` python
A = math.pi**2 * R
a = math.pi**2 * r
```

che rappresentano?

**Comment by Teodoro777** [comment]
Sono l'area della circonferenza maggiore (R) e area della circonferenza
minore (r)

2016-10-30 12:24 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
e perché non crei una funzione per il calcolo dell'area di un cerchio?

**Comment by Teodoro777** [comment]
Fatto
