### ISSUE TITLE
cifre significative

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/recupero_python#8]
quando una funzione calcola un valore float dovrebbe restituire tutte le cifre che può (senza round).
Invece quando viene stampato un valore float, oppure quando devi fare il test della funzione, allora devi arrotondare

**Comment by Teodoro777** [comment]
Vabbè ma quando stampo è diverso, basta fare un '%.n' il test prende il
risultato grezzo della funzione.. Quindi come arrotondo?

2016-10-30 12:24 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ahe, sempre nello stesso modo.
però non devi confondere il test e la stampa con il valore di ritorno della funzione

**Comment by Teodoro777** [comment]
Dove lo devo mettere quel round se non nel return?

**Comment by FabioZTessitore** [comment]
lo devi mettere dove serve, per l'ennesima volta:
1) quando si stampa
2) quando si fa il test

**Comment by Teodoro777** [comment]
Il test legge il return..

**Comment by FabioZTessitore** [comment]
guarda

**Comment by Teodoro777** [comment]
Come mai nel round metto due cifre, ma ne stampa solo una dopo la virgola?

**Comment by FabioZTessitore** [comment]
è un caso (la seconda è 0), cambia i numeri e vedi

**Comment by Teodoro777** [comment]
Ahaha ok
