### ISSUE TITLE
cai

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/recupero_python#9]
carica  il programma cai che hai fatto in C in una cartella e trasformalo in python

**Comment by Teodoro777** [comment]
Perchè non facciamo una issue in cai così creo le due cartelle in due
linguaggi?

2016-10-31 10:55 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ok, ma devi riaggiungermi
